import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ReactQueryProvider } from "./react-query-provider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { AppBar, Stack, Toolbar, Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ReactQueryProvider>
            <AppBar position="static">
              <Toolbar>
                <Stack direction="row" gap={2}>
                  <Typography variant="h6" component={Link} href="/">
                    Home
                  </Typography>
                  <Typography variant="h6" component={Link} href="/api-docs">
                    Api Docs
                  </Typography>
                  <Typography variant="h6" component={Link} href="/crud">
                    Crud
                  </Typography>
                </Stack>
              </Toolbar>
            </AppBar>
            <main className="container mx-auto px-4">{children}</main>
          </ReactQueryProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
